/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'

export interface ApiDefinitionInput {
    [k: string]: {
        [k: string]: {
            lambda?: {
                invoke_arn: string
                function_name: string
                [k: string]: unknown
            }
            authorizer?: {
                lambda?: {
                    invoke_arn: string
                    function_name: string
                    [k: string]: unknown
                }
                name: string
                authorizerType?: string
                identitySource?: string
                header?: string
                cacheTtl?: number
                [k: string]: unknown
            }
            [k: string]: unknown
        }
    }
}

export const ApiDefinitionInput = {
    validate: (await import('./schemas/api-definition-input.schema.js'))
        .validate10 as unknown as ValidateFunction<ApiDefinitionInput>,
    get schema() {
        return ApiDefinitionInput.validate.schema
    },
    get errors() {
        return ApiDefinitionInput.validate.errors ?? undefined
    },
    is: (o: unknown): o is ApiDefinitionInput => ApiDefinitionInput.validate(o) === true,
} as const

export interface ApiDefinitionInputStringified {
    definition: string
    extensions: string
}

export const ApiDefinitionInputStringified = {
    validate: (await import('./schemas/api-definition-input-stringified.schema.js'))
        .validate10 as unknown as ValidateFunction<ApiDefinitionInputStringified>,
    get schema() {
        return ApiDefinitionInputStringified.validate.schema
    },
    get errors() {
        return ApiDefinitionInputStringified.validate.errors ?? undefined
    },
    is: (o: unknown): o is ApiDefinitionInputStringified => ApiDefinitionInputStringified.validate(o) === true,
} as const
